import 'package:isar/isar.dart';

part 'task.g.dart'; // Auto-generated by build_runner — do not create this manually

enum DateRule { specificDate, everyday, deadline, specificDays }
enum MetricType { boolean, numeric }

@collection
class Task {
  Id id = Isar.autoIncrement; // Isar assigns a unique number automatically

  late String uuid;       // Human-readable unique ID (for logs to reference)
  late String title;      // e.g. 'Morning Walk'
  late String description;
  late String tagUuid;    // Which tag/category this task belongs to

  @Enumerated(EnumType.name)
  late MetricType metricType; // boolean = checkbox, numeric = track a number

  String? metricUnit;     // e.g. 'steps', 'km' — null if boolean
  late double metricTarget; // e.g. 10000 for steps, 1.0 for a checkbox

  @Enumerated(EnumType.name)
  late DateRule dateRule;

  late DateTime startDate;
  DateTime? endDate;      // Only used for deadline tasks

  late int currentStreak;
  DateTime? lastCompletedDate;

  // For specificDays rule: 1=Monday, 2=Tuesday ... 7=Sunday
  late List<int> specificDays;

  Task();
}
